-- Format for overwriting define values:
--
NDefines.NDiplomacy.MAX_CLIENT_STATES = 100
NDefines.NGame.MAX_COLONIAL_NATIONS = 100
NDefines.NCountry.MAX_CROWN_COLONIES = 2

-- Test
NDefines.NAI.AGGRESSIVENESS = 200
NDefines.NAI.AGGRESSIVENESS_BONUS_EASY_WAR = 350
NDefines.NAI.DIPLOMATIC_ACTION_FABRICATE_CLAIM_HRE_FACTOR = 0.2
NDefines.NAI.DIPLOMATIC_ACTION_FABRICATE_CLAIM_HRE_EMPEROR_FACTOR = 0
NDefines.NAI.CONQUEST_INTEREST_DISTANCE = 60
NDefines.NAI.PEACE_TERMS_ANNEX_BASE_MULT = 20.0
NDefines.NAI.PEACE_TERMS_PROVINCE_CORE_MULT = 16.0
NDefines.NAI.PEACE_TERMS_PROVINCE_CLAIM_MULT = 8.0
NDefines.NAI.PEACE_TERMS_PROVINCE_NOT_CULTURE_MULT = 0.4
